server:
  port: 8082

spring:
  application:
    name: fitness-activity-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/fitness_activity
      database: fitness_activity
      username: root
      password: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
